### ISSUE TITLE
Formatting issues in Version History

### ISSUE THREAD

**Issue by gordlin** [ramp4-pcar4/storylines-editor#455] opened 2024-11-28 19:18 UTC
## Description

The Version History table sometimes doesn't take up all the space allocated to it.

## Screenshots

<img width="1113" alt="image" src="https://github.com/user-attachments/assets/0b383de9-5614-413b-8bca-3a36eeae45bd">

## Steps to reproduce

1. Go to any product with history (here, `00000000-0000-0000-0000-000000000000`)
2. Click `Show previous versions` in `Version History`
3. See formatting error.

**Comment by szczz** [comment] 2024-11-28 19:48
Closing, duplicate of #435

**Closed by szczz** 2024-11-28 19:48 UTC
Labels: Bug, UI/UX
