### ISSUE TITLE
Text is not centered in horizontal menu bubble

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#346] opened 2024-06-20 11:25 UTC
Found by Celina in 2024-06-18 Testing Party

## Description

This is an annoyance/UI - text is not centered in horizontal menu bubble

## Environment

- I used Edge + Nonylphenol Storyline

## Steps to reproduce

1. Click to Nonylphenol storyline. Change it to have a horizontal menu instead of vertical
2. Click Preview
3. Click different chapters

## Expected behavior

I expect the blue background around each chapter to be centered on the menu

## Actual behavior

It is not. Each ranges from slightly off center to greatly off-center.

**Comment by yileifeng** [comment] 2024-06-20 14:33
Related to/duplicate of https://github.com/ramp4-pcar4/storylines-editor/issues/328

**Closed** 2024-07-11 14:14 UTC
Labels: Bug, Quality Assurance
